### ISSUE TITLE
Latest 3828 Nightly build does not like older TerminatorPlugin 

### ISSUE THREAD

**Issue by Almighty188** [processhacker/plugins-extra#84]
As the latest TerminatorPlugin from plug-in extras would not build, [https://github.com/processhacker/plugins-extra/issues/83](url)

The trick of using older compiled .dll's does not work either. 

![2021-02-13_18-14-07](https://user-images.githubusercontent.com/78993393/107866680-25642780-6e28-11eb-8796-ba101da63636.jpg)

**Comment by VictorVG** [comment]
See https://github.com/processhacker/plugins-extra/issues/83

**Comment by Almighty188** [comment]
> See #83

Yes, that's why I referenced that in the OP.  #83 is compiling the plugin while I was talking about using a existing already built .dll for the plugin.

**Comment by dmex** [comment]
The plugin API was updated and PhOsVersion isn't exported anymore.

**Comment by Almighty188** [comment]
> The plugin API was updated and PhOsVersion isn't exported anymore.

Does this mean the plugin is supposed to build now?

**Comment by dmex** [comment]
@Almighty188 

It means the plugin needs to be updated with the newer version function but I haven't had the time to update the plugin yet because it's an archived plugin that isn't really supported anymore thanks to Valve Corporation and there have been more pressing bugs that need attention.

**Comment by Almighty188** [comment]
@dmex 
 
Thanks for the clarification.  Didn't realized the plugin was archived.  What did Valve Corporation do?

**Comment by dmex** [comment]
@Almighty188 

The plugin was fixed.

> What did Valve Corporation do?

They were permanently banning users from Steam after they used the terminator since most options trigger VAC.

TP2 creates a remote thread with ExitProcess but remote threads are banned.
TT2 changes the remote thread context to ExitProcess but changing thread context is banned.
CH1 duplicates and closes remote handles but duplicating handles is banned.
TD1 enables debug mode and immediately closes the debug object terminating the process but debugging is banned.
M1 writes zeros to the entire process (memset) but writing anything to memory is banned.
M2 changes the memory access to NOACCESS but blocking memory access is banned.

It doesn't matter that a remote thread is created with the ExitProcess address. Merely creating a thread triggered the bans without regard for the purpose and it's the same problem with the other termination options.

There was zero consideration given to tools like Terminator that can only terminate processes when they designed the anti-cheat so anything a third party process was doing to their process would trigger VAC and get you banned.

If Valve were using the ObRegisterCallbacks function then none of this would be an issue because those methods would be blocked and would not trigger those cheating checks but they refuse to use that function (as other vendors have done successfully) so we're in this position where the Terminator plugin had to be archived just so users wouldn't get their accounts permanently banned for trying to terminate their processes.

The other problem that caused this is related to faulty network drivers... Processes that use socket connections can deadlock and never terminate or exit because the network driver doesn't handle some network device IRPs correctly and some users who were unable to terminate the process (steam and/or games) would then attempt to use the Terminator plugin - which would also fail because of the hung IRP blocking process termination - but were immediately banned from Steam.

None of the things they've done prevents or stops cheating. All they've done instead is destroy tools like Terminator used to fight malware.

**Comment by Almighty188** [comment]
Thanks for taking the time to explain all that.  It seems they are basically punishing the good instead of the bad in reality.

**Comment by VictorVG** [comment]
It's easier and ... cheaper for them - why rewrite their own code if it is possible to prohibit what reveals their hack?
