### ISSUE TITLE
Fix Sandboxie plugin

### ISSUE THREAD

**Issue by kristibektashi** [processhacker/plugins-extra#85]
It doesn't work in latest Nightly build of Process Hacker (https://github.com/processhacker/processhacker/issues/233, https://github.com/processhacker/processhacker/issues/728). ~~Clearly the plugin is broken.~~ Nvm it wasn't the plugin

**Comment by dmex** [comment]
The sandboxie plugin was archived because its API abruptly terminates PH when it encounters an error:
https://github.com/processhacker/processhacker/issues/728#issuecomment-723663545

Third party libraries terminating PH cannot be supported - If they stop terminating the process then we can look into supporting it again.

**Comment by kristibektashi** [comment]
@dmex Who created the Sandboxie plugin?

**Comment by dmex** [comment]
There's no problem with the plugin... The problem is Sandboxie's library found in %ProgramFiles%\\Sandboxie\\SbieDll.dll

**Comment by kristibektashi** [comment]
~~Actually I tried it again and it somehow works just fine. I am using latest Process Hacker NIghtly and manually compiled all plugins (except TerminatorPlugin, for some reason it didn't work #86 ) and copied them to the plugins directory. I am also using the latest version of Sandboxie-plus (it by default installs in a different directory than the default on the plugin, I manually changed it to the corrent one)~~

Edit: aparently the mitigation policy was disabled in Process Hacker settings, still doesn't work with it enabled
